// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Auth from "../Context/Auth.bs.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Institution from "../Context/Institution.bs.js";
import * as Institutions from "../API/Institutions.bs.js";
import * as LoadingScreen from "../Components/LoadingScreen.bs.js";

function AccountsLoading(Props) {
  var navigation = Props.navigation;
  Props.countdown;
  var match = React.useContext(Institution.context)[/* institutions */0];
  var setInstitutions = match[1];
  var updateInstitutions = function (param) {
    Institutions.get(/* () */0).then((function (ins) {
              Curry._1(setInstitutions, (function (param) {
                      return /* Got */[ins];
                    }));
              return Promise.resolve((navigation.navigate("Accounts"), /* () */0));
            })).catch((function (error) {
            console.log(error);
            Curry._1(setInstitutions, (function (param) {
                    return /* Failed */2;
                  }));
            return Promise.resolve(Auth.logOut(navigation));
          }));
    return /* () */0;
  };
  React.useEffect((function () {
          Curry._1(setInstitutions, (function (param) {
                  return /* Loading */1;
                }));
          updateInstitutions(/* () */0);
          return (function (param) {
                    return /* () */0;
                  });
        }), ([]));
  return React.createElement(LoadingScreen.make, { });
}

var make = AccountsLoading;

export {
  make ,
  
}
/* Auth Not a pure module */
