// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as List from "bs-platform/lib/es6/list.js";
import * as React from "react";
import * as Institution from "../Context/Institution.bs.js";
import * as AccountsList from "../Components/AccountsList.bs.js";
import * as GlobalStyles from "../GlobalStyles.bs.js";
import * as ReactNavigation from "react-navigation";

function Accounts$CurrentAccounts(Props) {
  var navigation = Props.navigation;
  var match = React.useContext(Institution.context)[/* institutions */0];
  var institutions = match[0];
  if (typeof institutions === "number") {
    return null;
  } else {
    var filteredInstitutions = List.filter((function (i) {
              return i[/* consentStatus */0] !== /* AwaitingAuthorization */0;
            }))(institutions[0]);
    var match$1 = List.partition((function (i) {
            return i[/* consentStatus */0] === /* Expired */5;
          }), filteredInstitutions);
    var expiredAuth = match$1[0];
    var match$2 = List.length(expiredAuth) === 0;
    return React.createElement(AccountsList.List[/* make */1], {
                institutions: List.append(expiredAuth, match$1[1]),
                navigation: navigation,
                canAdd: true,
                heading: match$2 ? "Accounts you've linked with Sumi" : String(List.length(expiredAuth)) + " of your accounts require reauthorisation"
              });
  }
}

Accounts$CurrentAccounts.navigationOptions = {
  title: "Authorized"
};

var CurrentAccounts = /* module */[/* make */Accounts$CurrentAccounts];

function Accounts$OtherAccounts(Props) {
  var navigation = Props.navigation;
  var match = React.useContext(Institution.context)[/* institutions */0];
  var institutions = match[0];
  if (typeof institutions === "number") {
    return null;
  } else {
    return React.createElement(AccountsList.List[/* make */1], {
                institutions: List.filter((function (i) {
                          return i[/* consentStatus */0] === /* AwaitingAuthorization */0;
                        }))(institutions[0]),
                navigation: navigation,
                canAdd: false,
                heading: "Select a bank to link it to your Sumi account"
              });
  }
}

Accounts$OtherAccounts.navigationOptions = {
  title: "Other"
};

var OtherAccounts = /* module */[/* make */Accounts$OtherAccounts];

var $$navigator = ReactNavigation.createMaterialTopTabNavigator({
      CurrentAccounts: Accounts$CurrentAccounts,
      OtherAccounts: Accounts$OtherAccounts
    }, {
      tabBarOptions: {
        activeTintColor: GlobalStyles.colors[/* primary */1],
        inactiveTintColor: GlobalStyles.colors[/* inactive */3],
        indicatorStyle: {
          backgroundColor: GlobalStyles.colors[/* primary */1]
        },
        style: {
          backgroundColor: GlobalStyles.colors[/* textLight */5]
        }
      }
    });

$$navigator.navigationOptions = {
  headerTitle: "Accounts",
  headerTitleStyle: {
    fontWeight: "bold"
  }
};

export {
  CurrentAccounts ,
  OtherAccounts ,
  $$navigator ,
  
}
/*  Not a pure module */
