// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Auth from "../Context/Auth.bs.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as LoadingScreen from "../Components/LoadingScreen.bs.js";

function AuthLoading(Props) {
  var navigation = Props.navigation;
  Props.countdown;
  var match = React.useContext(Auth.context)[/* auth */0];
  var setUser = match[1];
  var checkAuthWithRoute = function (param) {
    Auth.getCurrentUser(/* () */0).then((function (user) {
                return Promise.resolve(Curry._1(setUser, (function (param) {
                                  return user;
                                })));
              })).then((function (param) {
              return Promise.resolve((navigation.navigate("App"), /* () */0));
            })).catch((function (_err) {
            return Promise.resolve(Auth.logOut(navigation));
          }));
    return /* () */0;
  };
  React.useEffect((function () {
          checkAuthWithRoute(/* () */0);
          return (function (param) {
                    return /* () */0;
                  });
        }), ([]));
  return React.createElement(LoadingScreen.make, { });
}

var make = AuthLoading;

export {
  make ,
  
}
/* Auth Not a pure module */
