// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Auth from "../Context/Auth.bs.js";
import * as Expo from "expo";
import * as React from "react";
import * as GlobalStyles from "../GlobalStyles.bs.js";
import * as ReactNative from "react-native";
import * as SearchParams from "search-params";
import * as VectorIcons from "@expo/vector-icons";

function Dashboard(Props) {
  var navigation = Props.navigation;
  var match = React.useContext(Auth.context)[/* auth */0];
  var user = Auth.currentUserOrRaise(match[0]);
  var url = Expo.Linking.makeUrl("accounts", /* () */0);
  console.log(SearchParams.parse("http://localhost:8080/?consent=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJJTlNUSVRVVElPTiI6ImJidmEtc2FuZGJveCIsIkNPTlNFTlQiOiIwZDc0NGJhZC04ZDczLTQ5NDMtODEyYS1hYTI5ODJhODMwMDYiLCJBUFBMSUNBVElPTl9VU0VSX0lEIjoiYUBmLmNvbSIsIlVTRVIiOiI4OGM4ZWE2Yy0yNWEzLTRlY2ItYjEzNC1hNGIyM2RkZTJkZjcifQ.lGhpcwuFEkzu7YrpyoPh-Pretpmw1HVz0gU9NBJXA4xFgaqlAF8GDtemaE-gWM_m6_pPY3hWLPaYxZGelAvsfw&application-user-id=a%40f.com&user-uuid=88c8ea6c-25a3-4ecb-b134-a4b23dde2df7&institution=bbva-sandbox"));
  return React.createElement(ReactNative.View, {
              style: GlobalStyles.styles.container,
              children: null
            }, React.createElement(ReactNative.Text, {
                  children: "Welcome to the dashboard " + user[/* name */1]
                }), React.createElement(ReactNative.Button, {
                  onPress: (function (param) {
                      return Auth.logOut(navigation);
                    }),
                  title: "Sign Out"
                }), React.createElement(ReactNative.Button, {
                  onPress: (function (param) {
                      console.log(url);
                      ReactNative.Linking.openURL(url).catch((function (err) {
                              return Promise.resolve((console.log(err), /* () */0));
                            }));
                      return /* () */0;
                    }),
                  title: "Test?"
                }));
}

Dashboard.navigationOptions = {
  tabBarIcon: (function (props) {
      return React.createElement(VectorIcons.AntDesign, {
                  name: "dashboard",
                  size: 22,
                  color: props.tintColor
                });
    })
};

var make = Dashboard;

export {
  make ,
  
}
/*  Not a pure module */
