// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactNative from "react-native";
import * as LoadingScreen from "../Components/LoadingScreen.bs.js";
import * as SearchParams from "search-params";

function authSuccess(url) {
  var match = url.match(new RegExp("localhost:8080"));
  return match !== null;
}

function Webview(Props) {
  var navigation = Props.navigation;
  var match = navigation.getParam("uri");
  var uri = (match == null) ? (navigation.goBack(), "") : match;
  return React.createElement(ReactNative.WebView, {
              onError: (function ($$event) {
                  console.log($$event);
                  navigation.navigate("Accounts");
                  return /* () */0;
                }),
              onShouldStartLoadWithRequest: (function (e) {
                  if (authSuccess(e.url)) {
                    console.log(SearchParams.parse(e.url));
                  }
                  return true;
                }),
              renderLoading: (function (param) {
                  return React.createElement(LoadingScreen.make, { });
                }),
              source: {
                uri: uri
              }
            });
}

var make = Webview;

export {
  authSuccess ,
  make ,
  
}
/* react Not a pure module */
