// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as GlobalStyles from "../GlobalStyles.bs.js";
import * as ReactNative from "react-native";

function LoadingScreen(Props) {
  var match = Props.countdown;
  var countdown = match !== undefined ? match : 3;
  var match$1 = React.useState((function () {
          return countdown;
        }));
  var setCount = match$1[1];
  React.useEffect((function () {
          var intervalId = setInterval((function (param) {
                  return Curry._1(setCount, (function (count) {
                                return count - 1 | 0;
                              }));
                }), 1000);
          return (function (param) {
                    clearInterval(intervalId);
                    return /* () */0;
                  });
        }), ([]));
  var match$2 = match$1[0] === 0;
  return React.createElement(ReactNative.View, {
              style: GlobalStyles.styles.container,
              children: null
            }, match$2 ? React.createElement(ReactNative.ActivityIndicator, { }) : null, React.createElement(ReactNative.StatusBar, {
                  barStyle: "default"
                }));
}

var make = LoadingScreen;

export {
  make ,
  
}
/* react Not a pure module */
