// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";

var context = React.createContext(/* record */[/* institutions : tuple */[
        /* NotAsked */0,
        (function (param) {
            return /* () */0;
          })
      ]]);

function makeProps(value, children, param) {
  return {
          value: value,
          children: children
        };
}

var make = context.Provider;

var Provider = /* module */[
  /* makeProps */makeProps,
  /* make */make
];

export {
  context ,
  Provider ,
  
}
/* context Not a pure module */
