// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Auth from "./Context/Auth.bs.js";
import * as React from "react";
import * as GlobalStyles from "./GlobalStyles.bs.js";
import * as ReactNative from "react-native";

function Accounts(Props) {
  var match = React.useContext(Auth.context)[/* auth */0];
  var user = Auth.currentUserOrRaise(match[0]);
  return React.createElement(ReactNative.View, {
              style: GlobalStyles.styles.container,
              children: React.createElement(ReactNative.Text, {
                    children: "Welcome to the accounts page " + user[/* name */1]
                  })
            });
}

var make = Accounts;

export {
  make ,
  
}
/* Auth Not a pure module */
