// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Auth from "./Context/Auth.bs.js";
import * as React from "react";
import * as AppNavigator from "./AppNavigator.bs.js";

function App$app(Props) {
  var match = React.useState((function () {
          return /* LoggedOut */0;
        }));
  var auth = match[0];
  var match$1 = React.useState((function () {
          return "";
        }));
  var token = match$1[0];
  return React.createElement(Auth.Provider[/* make */1], Auth.Provider[/* makeProps */0](/* record */[
                  /* auth : tuple */[
                    auth,
                    match[1]
                  ],
                  /* token : tuple */[
                    token,
                    match$1[1]
                  ]
                ], React.createElement(AppNavigator.SumiAppContainer[/* make */0], {
                      screenProps: {
                        token: token,
                        auth: auth
                      }
                    }), /* () */0));
}

var app = App$app;

export {
  app ,
  
}
/* Auth Not a pure module */
