// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";
import * as SignIn from "./Pages/SignIn.bs.js";
import * as Webview from "./Pages/Webview.bs.js";
import * as Accounts from "./Pages/Accounts.bs.js";
import * as Dashboard from "./Pages/Dashboard.bs.js";
import * as AuthLoading from "./Pages/AuthLoading.bs.js";
import * as GlobalStyles from "./GlobalStyles.bs.js";
import * as AccountsLoading from "./Pages/AccountsLoading.bs.js";
import * as ReactNavigation from "react-navigation";
import * as VectorIcons from "@expo/vector-icons";
import * as AppContainer$ReactNavigation from "reason-react-navigation/src/AppContainer.bs.js";

var routes = {
  SignIn: SignIn.make
};

var $$navigator = ReactNavigation.createStackNavigator(routes, {
      mode: "modal",
      headerMode: "none"
    });

var AuthStack = /* module */[
  /* routes */routes,
  /* navigator */$$navigator
];

var routes$1 = {
  Accounts: Accounts.$$navigator,
  Webview: Webview.make
};

ReactNavigation.createStackNavigator(routes$1).navigationOptions = {
  tabBarIcon: (function (props) {
      return React.createElement(VectorIcons.MaterialIcons, {
                  name: "account-balance",
                  size: 22,
                  color: props.tintColor
                });
    })
};

var $$navigator$1 = ReactNavigation.createSwitchNavigator({
      AccountsLoading: AccountsLoading.make,
      Accounts: ReactNavigation.createStackNavigator(routes$1)
    }, {
      initialRouteName: "AccountsLoading"
    });

$$navigator$1.navigationOptions = {
  tabBarIcon: (function (props) {
      return React.createElement(VectorIcons.MaterialIcons, {
                  name: "account-balance",
                  size: 22,
                  color: props.tintColor
                });
    })
};

var AccountsStack = /* module */[
  /* routes */routes$1,
  /* accountsNavigator : () */0,
  /* navigator */$$navigator$1
];

var routes$2 = {
  Accounts: $$navigator$1,
  Dashboard: Dashboard.make
};

var $$navigator$2 = ReactNavigation.createBottomTabNavigator(routes$2, {
      tabBarOptions: {
        activeTintColor: GlobalStyles.colors[/* primary */1],
        inactiveTintColor: "grey"
      }
    });

var AppStack = /* module */[
  /* routes */routes$2,
  /* navigator */$$navigator$2
];

var $$navigator$3 = ReactNavigation.createSwitchNavigator({
      App: $$navigator$2,
      Auth: $$navigator,
      AuthLoading: AuthLoading.make
    }, {
      initialRouteName: "AuthLoading"
    });

var SumiAppContainer = AppContainer$ReactNavigation.Make(/* module */[/* navigator */$$navigator$3]);

export {
  AuthStack ,
  AccountsStack ,
  AppStack ,
  SumiAppContainer ,
  
}
/* navigator Not a pure module */
