// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Auth from "./Context/Auth.bs.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as GlobalStyles from "./GlobalStyles.bs.js";
import * as ReactNative from "react-native";

function AuthLoading(Props) {
  var navigation = Props.navigation;
  var match = Props.countdown;
  var countdown = match !== undefined ? match : 3;
  var match$1 = React.useContext(Auth.context)[/* auth */0];
  var setAuth = match$1[1];
  var match$2 = React.useState((function () {
          return countdown;
        }));
  var setCount = match$2[1];
  React.useEffect((function () {
          var intervalId = setInterval((function (param) {
                  return Curry._1(setCount, (function (count) {
                                return count - 1 | 0;
                              }));
                }), 1000);
          return (function (param) {
                    clearInterval(intervalId);
                    return /* () */0;
                  });
        }), ([]));
  React.useEffect((function () {
          Auth.checkAuthWithRoute(navigation, setAuth);
          return (function (param) {
                    return /* () */0;
                  });
        }), /* array */[]);
  var match$3 = match$2[0] === 0;
  return React.createElement(ReactNative.View, {
              style: GlobalStyles.styles.container,
              children: null
            }, match$3 ? React.createElement(ReactNative.ActivityIndicator, { }) : null, React.createElement(ReactNative.StatusBar, {
                  barStyle: "default"
                }));
}

var make = AuthLoading;

export {
  make ,
  
}
/* Auth Not a pure module */
