// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactNative from "react-native";

var styles = ReactNative.StyleSheet.create({
      container: {
        backgroundColor: "#F5FCFF",
        alignItems: "center",
        flex: 1,
        justifyContent: "center"
      }
    });

function Dashboard(Props) {
  var navigation = Props.navigation;
  return React.createElement(ReactNative.View, {
              style: styles.container,
              children: null
            }, React.createElement(ReactNative.Text, {
                  children: "Welcome to the dashboard"
                }), React.createElement(ReactNative.Button, {
                  onPress: (function (param) {
                      navigation.navigate("SignIn");
                      return /* () */0;
                    }),
                  title: "Sign Out"
                }));
}

var make = Dashboard;

export {
  styles ,
  make ,
  
}
/* styles Not a pure module */
