// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Auth from "./Context/Auth.bs.js";
import * as React from "react";
import * as GlobalStyles from "./GlobalStyles.bs.js";
import * as ReactNative from "react-native";
import * as VectorIcons from "@expo/vector-icons";

var Ionicons = /* module */[];

function Dashboard(Props) {
  var navigation = Props.navigation;
  var match = React.useContext(Auth.context)[/* auth */0];
  var user = Auth.currentUserOrRaise(match[0]);
  return React.createElement(ReactNative.View, {
              style: GlobalStyles.styles.container,
              children: null
            }, React.createElement(ReactNative.Text, {
                  children: "Welcome to the dashboard " + user[/* name */1]
                }), React.createElement(ReactNative.Button, {
                  onPress: (function (param) {
                      return Auth.logOut(navigation);
                    }),
                  title: "Sign Out"
                }));
}

Dashboard.navigationOptions = {
  tabBarIcon: (function (_props) {
      return React.createElement(VectorIcons.AntDesign, {
                  name: "dashboard",
                  size: 22
                });
    })
};

var make = Dashboard;

export {
  Ionicons ,
  make ,
  
}
/*  Not a pure module */
