// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as ReactNative from "react-native";
import * as Style$ReactNative from "reason-react-native/src/apis/Style.bs.js";

var styles = ReactNative.StyleSheet.create({
      container: {
        backgroundColor: "#F5FCFF",
        alignItems: "center",
        flex: 1,
        justifyContent: "center"
      },
      textInput: {
        fontSize: 20,
        borderBottomWidth: 1,
        borderColor: "#CCCCCC",
        height: 50,
        marginTop: 15,
        paddingLeft: 20,
        paddingRight: 20,
        width: Style$ReactNative.pct(85)
      },
      errorText: {
        color: "#ff0033",
        marginTop: 15
      },
      submitButton: {
        backgroundColor: "#053CC8",
        marginTop: 25,
        width: Style$ReactNative.pct(85)
      },
      headingText: {
        fontSize: 20,
        marginTop: 25
      }
    });

export {
  styles ,
  
}
/* styles Not a pure module */
