// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE


var Ionicons = /* module */[];

var AntDesign = /* module */[];

var Material = /* module */[];

export {
  Ionicons ,
  AntDesign ,
  Material ,
  
}
/* No side effect */
