// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";

function focusRef(ref) {
  Belt_Option.map(Caml_option.nullable_to_opt(ref.current), (function (ref) {
          return ref.focus();
        }));
  return /* () */0;
}

export {
  focusRef ,
  
}
/* No side effect */
